#!/bin/bash
#
# pre-commit hook

set -e

function api_spotless_check() {
  cd api

  if ./gradlew spotlessCheck; then
    echo '[API]: Good format'
  else
    ./gradlew spotlessApply
    echo '[API]: Bad format, spotless applied. Check the changed files again'
    exit 1
  fi

  cd ..
}

# pre-commit api check
function pre_commit_api_check() {
  api_spotless_check
}

# pre-commit web check
function pre_commit_web_check() {
  web_lint_check
}

function web_lint_check() {
  cd web
  ng lint
  npx prettier . --check
  cd ..
}

is_web_changed=false

for f in $(git diff --name-only HEAD); do
  if [[ $f =~ ^api\/* ]]; then
    pre_commit_api_check
  fi
  if [[ $f =~ ^web\/* ]]; then
    is_web_changed=true
  fi
done

if [ $is_web_changed = true ]; then
  pre_commit_web_check
fi
